package output

import (
	"fmt"
	"os"
	"time"
)

func GenerateHTMLReport(path string, title string, data map[string]string) error {
	timestamp := time.Now().Format("2006-01-02 15:04:05")

	html := `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>` + title + ` - ReconX-Go Report</title>
<style>
body { font-family: Arial, sans-serif; background: #0d1117; color: #e6edf3; padding: 20px; }
h1 { color: #58a6ff; }
.card {
    background: #161b22;
    padding: 18px;
    margin-bottom: 15px;
    border-radius: 8px;
    border: 1px solid #30363d;
}
.key { font-weight: bold; color: #79c0ff; }
.value { color: #c9d1d9; }
.footer { margin-top: 30px; font-size: 14px; color: #8b949e; }
</style>
</head>
<body>

<h1>ReconX-Go Report</h1>
<p>Generated at: ` + timestamp + `</p>
<hr>
`

	for k, v := range data {
		html += `
<div class="card">
    <div class="key">` + k + `</div>
    <div class="value">` + v + `</div>
</div>`
	}

	html += `
<div class="footer">
Generated by ReconX-Go Framework — by Ahmed Ibrahim
</div>

</body>
</html>
`

	return os.WriteFile(path, []byte(html), 0644)
}
